// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMCz0r1X_PHFhqyjaEOQ6IVX6v8Ayi0Is',
    appId: '1:282185173775:android:3fee594e7ce7bf0a834c7a',
    messagingSenderId: '282185173775',
    projectId: 'kigali-directory-b8972',
    storageBucket: 'kigali-directory-b8972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcBX94KS8XcfdTmw7PPICl-t5NOaOUZmg',
    appId: '1:282185173775:ios:b70236ac3ce1e14c834c7a',
    messagingSenderId: '282185173775',
    projectId: 'kigali-directory-b8972',
    storageBucket: 'kigali-directory-b8972.firebasestorage.app',
    iosBundleId: 'com.kigali.kigaliDirectory',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkO2SB-bvRhLWTkkDZd7MUN0iAEmJ5-M',
    appId: '1:282185173775:web:3d1a1fe45f188d45834c7a',
    messagingSenderId: '282185173775',
    projectId: 'kigali-directory-b8972',
    authDomain: 'kigali-directory-b8972.firebaseapp.com',
    storageBucket: 'kigali-directory-b8972.firebasestorage.app',
  );
}
